name: Terraform EC2 Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      
    defaults:
      run:
        working-directory: Terraform  # 👈 points to your Terraform folder

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Inject SSH Private Key
      run: |
        echo "$SSH_PRIVATE_KEY" > key.pem
        chmod 600 key.pem

    - name: Get EC2 Public IP
      run: echo "EC2_IP=$(terraform output -raw public_ip)" >> $GITHUB_ENV
      
    - name: Copy src folder and run setup on EC2
      run: |
        # Create destination folder on EC2
        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ env.EC2_IP }} "mkdir -p ~/app"
        # Copy src folder to EC2
        scp -o StrictHostKeyChecking=no -i key.pem -r src/ ec2-user@${{ env.EC2_IP }}:~/app/
        # Run setup.sh on EC2
        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ env.EC2_IP }} "bash -s" < scripts/setup.sh



